version: '3.3'

services:
# Gracefully starts:
# - Three Cassandra 3.11 backends with included Management API
# - One Stargate node offering REST, GraphQL and Document endpoints

  backend-1:
    image: datastax/cassandra-mgmtapi-3_11_10:v0.1.23
    container_name: backend-1
    networks:
      - backend
    ports:
      # Management API (http://localhost:9081/api/v0/probes/liveness)
      - 9081:8080
    environment:
      - HEAP_NEWSIZE=2G
      - MAX_HEAP_SIZE=4G
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=stargate
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: curl --fail http://localhost:8080/api/v0/probes/liveness || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  backend-2:
    image: datastax/cassandra-mgmtapi-3_11_10:v0.1.23
    container_name: backend-2
    networks:
      - backend
    ports:
      # Management API (http://localhost:9082/api/v0/probes/liveness)
      - 9082:8080
    depends_on:
      - backend-1
    environment:
      - HEAP_NEWSIZE=2G
      - MAX_HEAP_SIZE=4G
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=stargate
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: curl --fail http://localhost:8080/api/v0/probes/liveness || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      backend-1:
        condition: service_healthy

  backend-3:
    image: datastax/cassandra-mgmtapi-3_11_10:v0.1.23
    container_name: backend-3
    networks:
      - backend
    ports:
      # Management API (http://localhost:9083/api/v0/probes/liveness)
      - 9083:8080
    depends_on:
      - backend-2
    environment:
      - HEAP_NEWSIZE=2G
      - MAX_HEAP_SIZE=4G
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=stargate
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: curl --fail http://localhost:8080/api/v0/probes/liveness || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      backend-2:
        condition: service_healthy

  stargate:
    image: stargateio/stargate-3_11:v1.0.11
    container_name: stargate
    depends_on: 
      - backend-1
    networks:
      - backend
    ports:
      # GraphQL interface for CRUD (http://localhost:8080/api/playground)
      - 8080:8080
      # Rest authorization (token)
      - 8081:8081
      # REST for CRUD (http://localhost:8082/swagger-ui)
      - 8082:8082
      # CQL Service
      - 9042:9042
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=stargate
      - CLUSTER_VERSION=3.11
      - SEED=backend-1
      - DATACENTER_NAME=dc1
      - RACK_NAME=rack1
    depends_on:
      backend-3:
        condition: service_healthy

networks:
  backend: