version: '3.3'

services:

  backend-1:
    image: cassandra:3.11
    container_name: backend-1
    networks:
      - backend
    environment:
      - HEAP_NEWSIZE=2G
      - MAX_HEAP_SIZE=4G
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=stargate
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool status | grep -c UN) = 1 ]"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend-2:
    image: cassandra:3.11
    container_name: backend-2
    networks:
      - backend
    depends_on:
      - backend-1
    environment:
      - HEAP_NEWSIZE=2G
      - MAX_HEAP_SIZE=4G
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=stargate
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool status | grep -c UN) = 2 ]"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      backend-1:
        condition: service_healthy

  backend-3:
    image: cassandra:3.11
    container_name: backend-3
    networks:
      - backend
    depends_on:
      - backend-2
    environment:
      - HEAP_NEWSIZE=2G
      - MAX_HEAP_SIZE=4G
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=stargate
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool status | grep -c UN) = 3 ]"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      backend-2:
        condition: service_healthy

  stargate:
    image: stargateio/stargate-3_11:v1.0.11
    container_name: stargate
    depends_on: 
      - backend-1
    networks:
      - backend
    ports:
      # CQL Service
      - 9042:9042
      # GraphQL interface for CRUD
      - 8080:8080
      # Rest authorization (token)
      - 8081:8081
      # REST for CRUD localhost:8082/swagger-ui
      - 8082:8082
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=stargate
      - CLUSTER_VERSION=3.11
      - SEED=docker-compose-stargate-cassandra-1
      - DATACENTER_NAME=dc1
      - RACK_NAME=rack1
    depends_on:
      backend-3:
        condition: service_healthy

networks:
  backend: